# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
- script: dotnet --list-runtimes
- script: dotnet --list-sdks
- script: dotnet --version
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'ValueUtilsTest/ValueUtilsTest.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
#- script: dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
